config/routes.rb
Rails.application.routes.draw do
  resources :animals do
    resources :sightings
  end
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  validates :animal_name, :presence => true
  has_many :sightings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  validates :latitude, :presence => true
  belongs_to :animal
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.all
    render :index
  end
  def show
  @animal = Animal.find(params[:id])
    render :show
  end
  def new
    @animal = Animal.new
    render :new
  end
  def create
    @animal = Animal.new(animal_params)
    if @animal.save
      redirect_to animals_path
    else
      render :new
    end
  end

  def edit
    @animal = Animal.find(params[:id])
    render :edit
  end

  def update
    @animal = Animal.find(params[:id])
    if @animal.update(animal_params)
      redirect_to animals_path
    else
      render :edit
    end
  end
  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    redirect_to animals_path
  end
private
  def animal_params
    params.require(:animal).permit(:animal_name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  def new
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.new
  end

  def create
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.new(sighting_params)
    if @sighting.save
      redirect_to animal_path(@sighting.animal)
    else
      render :new
    end
  end
  def destroy
    @animal = Animal.find(params[:animal_id])
    @sighting = Sighting.find(params[:id])
    @sighting.destroy
    redirect_to animal_path(@sighting.animal)
  end

  def edit
    @animal = Animal.find(params[:animal_id])
    @sighting = Sighting.find(params[:id])
    render :edit
  end
  def update

  end
private
 def sighting_params
   params.require(:sighting).permit(:location_name, :longitude, :latitude, :date_time)
 end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_form.html.erb
<%= render "layouts/errors", :object => @animal %>

<%= form_for @animal do |f|%>
  <%=f.label :animal_name %>
  <%=f.text_field :animal_name %>
  <%= f.submit%>
<%end%>

app/views/animals/edit.html.erb
<h1>Edit Animal</h1>

<%= render 'form'%>

app/views/animals/index.html.erb
<h3>Animals</h3>

<ul>
<% @animals.each do |animal|%>
  <li> <%= link_to animal.animal_name, animal_path(animal) %> </li>
<%end%>
</ul>

<%= link_to "New Animal", new_animal_path%>

app/views/animals/new.html.erb
<h3>Add Animal</h3>

<%= render "form"%>

app/views/animals/show.html.erb
<h3><%=@animal.animal_name%></h3>

<%if @animal.sightings.any?%>
<h3>Here are the sightings for this animal:</h3>
  <ul>
    <% @animal.sightings.each do |sighting|%>
      <li> <%= sighting.location_name %> </li>
      <li> <%=sighting.longitude %> </li>
      <li> <%=sighting.latitude %> </li>
      <li> <%=sighting.date_time %> </li>
      <p>
        <%= link_to "Edit", edit_animal_sighting_path(@animal, sighting)%> |
        <%= link_to "Delete", animal_sighting_path(@animal, sighting), :data => {:confirm => "Are you sure that you want to delete this sighting", :method => "delete"}%>
      </p>
    <% end %>
  </ul>
    <%else%>
    <p>
      There are no sightings yet for this animal!
    </p>
    <% end %>
<p>
  <%=link_to "Add Sighting", new_animal_sighting_path(@animal)%>
</p>
<p>
  <%=link_to "Edit", edit_animal_path(@animal)%>
</p>
<p>
  <%=link_to "Delete", animal_path(@animal), :data => {:confirm => "Are you sure?",
    :method => "delete"}%>
</p>
<p>
  <%=link_to "Go Back", animals_path %>

</p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors: </h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WildlifeTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sightings/_form.html.erb
<%= render "layouts/errors", :object => @sighting %>

<%= form_for [@animal, @sighting] do |f| %>
  <%=f.label :location_name %>
  <%=f.text_field :location_name %>
  <%=f.label :longitude %>
  <%=f.text_field :longitude %>
  <%=f.label :latitude %>
  <%=f.text_field :latitude %>
  <%=f.label :date_time %>
  <%=f.datetime_select :date_time %>
<p>
  <%=f.submit%>
</p>
<% end %>

app/views/sightings/edit.html.erb
<%= render "layouts/errors"%>

app/views/sightings/new.html.erb
<h1>Add a new sighting for <%= @animal.animal_name%></h1>
<%= render 'form' %>